dist: xenial
sudo: required
services:
  - xvfb
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 10
before_script:
  # Use a virtual display.
  - "export DISPLAY=:99.0"
install:
  - npm ci
script:
  - npm run lint
  - npm run test:once
  - npm run build
  - npm run e2e
